### ISSUE TITLE
[question] how to change the sound pitch?

### ISSUE THREAD

**Issue by yzqdev** [Keksuccino/Melody#2]
the [audioclip](https://github.com/Keksuccino/Melody/blob/1.20.1/common/src/main/java/de/keksuccino/melody/resources/audio/AudioClip.java) file doesn't have a `setPitch` method, how to change the pitch of music?

like 
```
...
clip.setPitch(1.1f)
clip.play();
```

**Comment by Keksuccino** [comment]
I think I never added that, sorry.
You would need to get the OpenAL source int from one of the subclasses of `AudioClip` and change the pitch directly via OpenAL. Kinda dirty, but that's the only way, sorry.

**Comment by yzqdev** [comment]
Got it, thank you
